# Generated by Django 3.2.1 on 2021-05-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'автора',
                'verbose_name_plural': 'Авторы',
                'ordering': ['first_name', 'second_name'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Название')),
                ('category_description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('link_name', models.URLField(max_length=150, verbose_name='Название ссылки')),
                ('count_visites', models.PositiveIntegerField(default=0, verbose_name='Кол-во переходов')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='links.authors')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='links.categories')),
            ],
            options={
                'verbose_name': 'ссылку',
                'verbose_name_plural': 'Ссылки',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
