# Generated by Django 3.2.1 on 2021-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'ссылку', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterField(
            model_name='links',
            name='count_visites',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во переходов'),
        ),
        migrations.AlterField(
            model_name='links',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='links',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='links',
            name='link_name',
            field=models.URLField(max_length=150, verbose_name='Название ссылки'),
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
    ]
